[LightDM]
run-directory = /run/lightdm

[Seat:*]
greeter-session = lightdm-gtk-greeter
greeter-hide-users = false
greeter-allow-guest = false
session-wrapper = /etc/lightdm/Xsession
autologin-user =
autologin-session = i3
user-session = i3

[XDMCPServer]
enabled=false

[VNCServer]
enabled=false
