[greeter]
background = /usr/share/backgrounds/pepaos-wallpaper.png
theme-name = Arc-Dark
icon-theme-name = Papirus-Dark
cursor-theme-name = breeze
font-name = JetBrains Mono 10
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %Y-%m-%d %H:%M
position = 50%,center 50%,center
screensaver-timeout = 60
