#!/usr/bin/env bash
# Pepa OS - archiso profile configuration

iso_name="pepaos"
iso_label="PEPAOS_$(date +%Y%m)"
iso_publisher="Pepa OS <https://pepaos.example.com>"
iso_application="Pepa OS Live/Rescue DVD"
iso_version="$(date +%Y.%m)"
install_dir="pepaos"
buildmodes="iso"
bootmodes="bios.syslinux.mbr bios.syslinux.eltorito" "uefi-ia32.grub.esp" "uefi-x64.grub.esp" "uefi-ia32.grub.eltorito" "uefi-x64.grub.eltorito"
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--long' '-19')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/gshadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/usr/local/bin/pepaos-welcome"]="0:0:755"
)
